
project_id = "qzcplkyinvndvhnevsbt"

[api]
# Disables schema caching, good for development but not for production
enabled_schemas = ["public", "storage", "graphql_public"]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
auto_confirm_new_users = true

[functions]
[functions.get-mapbox-token]
verify_jwt = true
[functions.get-weather-key]
verify_jwt = true
[functions.get-weather]
verify_jwt = true
[functions.import-trails]
verify_jwt = true

[[transformers]]
extensions = ["supabase_realtime"]
