// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbckwkjqrolfeqqvkigt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiY2t3a2pxcm9sZmVxcXZraWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjQzODgsImV4cCI6MjA2NjcwMDM4OH0.9Nh4xJt79k_yuUuTeM7IhwUSoz0mOyj5XVHNlgsA-MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);