// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzcplkyinvndvhnevsbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6Y3Bsa3lpbnZuZHZobmV2c2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzg1OTUsImV4cCI6MjA2MDYxNDU5NX0.ehgiR9tiAz4kbaMFaRI-loE7NI7eOfcvrE-gnutONQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);