// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egmshbdgldabocvalrxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbXNoYmRnbGRhYm9jdmFscnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTI3ODksImV4cCI6MjA2NTY4ODc4OX0.rhHIKM7NwflXMLu_8nX5tHTnv9OKn0oxs-TeE_kZLo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);